source 'https://rubygems.org'

gem 'activerecord'
gem 'activerecord-jdbc-adapter'
gem 'capybara', '3.20.2'
gem 'cucumber', '3.1.2'
gem 'rspec', '3.8.0'
gem 'ruby-oci8', '2.2.6.1'
gem 'syntax'
gem 'selenium-webdriver'
gem "yard-cucumber"
gem "redcarpet"
gem "rake"
gem "nokogiri", '1.10.2'